Loginscreen
MinGu-Jeong/BCSD_Beginner_Android pull request #1
Opened 2022-04-04 14:44 UTC by MinGu-Jeong

app/src/main/res/layout/ 경로에 xml파일 있습니다.
linearLayout, relativeLayout, ConstraintLayout 으로 LoginScreen을 만들었습니다.
linearLayout으로 만들었을때는 별 문제가 없었으나,
relativeLayout경우 회원가입 버튼이 가운데에 고정되버리면서 비밀번호찾기 버튼이 오른쪽으로 치우쳤고,
constraintLayout의 경우 구글, 네이버, 카카오 아이콘이 붙지 않아 서로 약간 띄어져있습니다.

2022-04-04 15:21 UTC, Yang-Seungmin requested changes
전반적으로 코드 컨벤션의 상태가 좋지 못하네요
1. XML 파일에서 View의 id를 정할 때 네이밍 규칙 한번 확인해주시고
2. 각 줄의 줄바꿈 및 들여쓰기 상태도 확인해 주세요. 어느 줄은 줄바꿈이 2줄이고 어디는 닫는 태그가 줄 바꾸고 있네요.
3. xml 태그 내에 body가 없으면 `/>`의 형식으로 태그를 닫습니다(`></ImageButton>` 이부분 체크).

다음 강의때 설명하겠지만 Android Studio 코드 작성중 Ctrl + Alt + L (⌘ + ⌥ + L on Mac) 키로 IDE 상에서 어느정도 자동 들여쓰기 수정을 할 수 있습니다.

레이아웃 구현은 완벽하진 않지만 차차 익히고 적응해 나가면 금방 하실 수 있을겁니다 ! 수고하셨습니다

2022-04-04 17:25 UTC, MinGu-Jeong commented
1. view id를 lowerCamelCase에서 snake_case로 변경하였습니다.
2. 줄바꿈 상태를 통일하였습니다.
3. /> 형식으로 태그를 닫도록 수정하였습니다.

2022-04-23 19:32 UTC, MinGu-Jeong commented
구글, 네이버, 카카오 아이콘 배열을 수정했습니다.

2022-04-25 10:56 UTC, Yang-Seungmin approved these changes
LGTM

2022-04-25 11:29 UTC, merged